version: '3.7'

services:
  rinkeby:
    command: ["--rpc", "--rpcapi", "eth,net", "--syncmode", "fast", "--rpcaddr", "0.0.0.0"]
    image: poktnetwork/geth:mainnet
    build: .
    expose:
      - "8545"
    ports:
      - "8545:8545"