version: '2'

volumes:
  geth-rinkeby: {}
  geth-mainnet: {}

services:
  geth-rinkeby:
    image: poktnetwork/geth:rinkeby
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:                                                                 
      - geth-rinkeby:/.rinkeby
    command: "--rinkeby --rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .testnet --verbosity 3"


  geth-mainnet:
    image: poktnetwork/geth:mainnet
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:                                                                 
      - geth-mainnet:/.mainnet
    command: "--rpc  --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3"
