version: '2'

services:
  geth:
    image: poktnetwork/geth
    build: .
    expose:
      - "8545"
    environment:
      RPCAPI: ${GETH_RPCAPI}
      NETWORKID: ${GETH_NETWORK_ID}
      SYNC_MODE: ${GETH_SYNC_MODE}

